## PyCaret の細かい使い方を実装

In [1]:
%load_ext lab_black

In [2]:
# ライブラリーのインポート
import pandas as pd
from pycaret.regression import *

# データセットの読込み
from pycaret.datasets import get_data

import warnings

warnings.simplefilter("ignore")

boston_data = get_data("boston")

# PyCaretを起動
exp1 = setup(boston_data, target="medv", ignore_features=None, session_id=42)

### Comparing All Models

In [3]:
# モデルの構築
top3 = compare_models(sort="MAE", n_select=3)

In [4]:
type(top3)

list

In [5]:
print(top3)

[<catboost.core.CatBoostRegressor object at 0x7f6ad437d490>, ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                    max_depth=None, max_features='auto', max_leaf_nodes=None,
                    max_samples=None, min_impurity_decrease=0.0,
                    min_impurity_split=None, min_samples_leaf=1,
                    min_samples_split=2, min_weight_fraction_leaf=0.0,
                    n_estimators=100, n_jobs=-1, oob_score=False,
                    random_state=42, verbose=0, warm_start=False), XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=-1, num_parallel_tree=1,
             objective='reg:squarederror', random_state=42, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='auto',
             validate_parameters=1, verbosity=0)]

### Create Model (with 5 Fold CV)

In [6]:
dt = create_model("dt", fold=5)

### Create Model (Metrics rounded to 2 decimals points)

In [7]:
rf = create_model("rf", round=2)

### Create Model (KNN)

In [8]:
knn = create_model("knn")

In [9]:
print(knn)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                    weights='uniform')

## Tune a Model

In [10]:
tuned_knn = tune_model(knn)

In [11]:
tuned_knn2 = tune_model(knn, n_iter=50)

In [12]:
plot_model(tuned_knn, plot="parameter")

              Parameters
algorithm           auto
leaf_size             30
metric         manhattan
metric_params       None
n_jobs                -1
n_neighbors            8
p                      2
weights          uniform

In [13]:
plot_model(tuned_knn2, plot="parameter")

              Parameters
algorithm           auto
leaf_size             30
metric         manhattan
metric_params       None
n_jobs                -1
n_neighbors            9
p                      2
weights         distance

## Ensemble a Model

In [14]:
# lets create a simple dt
dt = create_model("dt")

### Bagging

In [15]:
bagged_dt = ensemble_model(dt)

In [16]:
# check the parameter of bagged_dt
print(bagged_dt)

BaggingRegressor(base_estimator=DecisionTreeRegressor(ccp_alpha=0.0,
                                                      criterion='mse',
                                                      max_depth=None,
                                                      max_features=None,
                                                      max_leaf_nodes=None,
                                                      min_impurity_decrease=0.0,
                                                      min_impurity_split=None,
                                                      min_samples_leaf=1,
                                                      min_samples_split=2,
                                                      min_weight_fraction_leaf=0.0,
                                                      presort='deprecated',
                                                      random_state=42,
                                                      splitter='best'),
                 bootstrap=True, bootstrap_features=False, max_features=1.0,
                 max_samples=1.0, n_estimators=10, n_jobs=None, oob_score=False,
                 random_state=42, verbose=0, warm_start=False)

### Boosting

In [17]:
boosted_dt = ensemble_model(dt, method="Boosting")

In [18]:
bagged_dt2 = ensemble_model(dt, n_estimators=50)

### Blending

In [19]:
bagged_dt = ensemble_model(dt)

In [20]:
# check the parameter of bagged_dt
print(bagged_dt)

BaggingRegressor(base_estimator=DecisionTreeRegressor(ccp_alpha=0.0,
                                                      criterion='mse',
                                                      max_depth=None,
                                                      max_features=None,
                                                      max_leaf_nodes=None,
                                                      min_impurity_decrease=0.0,
                                                      min_impurity_split=None,
                                                      min_samples_leaf=1,
                                                      min_samples_split=2,
                                                      min_weight_fraction_leaf=0.0,
                                                      presort='deprecated',
                                                      random_state=42,
                                                      splitter='best'),
                 bootstrap=True, bootstrap_features=False, max_features=1.0,
                 max_samples=1.0, n_estimators=10, n_jobs=None, oob_score=False,
                 random_state=42, verbose=0, warm_start=False)

### Boosting

In [21]:
boosted_dt = ensemble_model(dt, method="Boosting")

In [22]:
bagged_dt2 = ensemble_model(dt, n_estimators=50)

### Blending

In [23]:
# train individual models to blend
lightgbm = create_model("lightgbm", verbose=False)
dt = create_model("dt", verbose=False)
lr = create_model("lr", verbose=False)

In [24]:
# blend individual models
blender = blend_models(estimator_list=[lightgbm, dt, lr])

In [25]:
# blend top3 models from compare_models
blender_top3 = blend_models(top3)

In [26]:
print(blender_top3.estimators_)

[<catboost.core.CatBoostRegressor object at 0x7f6ad00b7400>, ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                    max_depth=None, max_features='auto', max_leaf_nodes=None,
                    max_samples=None, min_impurity_decrease=0.0,
                    min_impurity_split=None, min_samples_leaf=1,
                    min_samples_split=2, min_weight_fraction_leaf=0.0,
                    n_estimators=100, n_jobs=-1, oob_score=False,
                    random_state=42, verbose=0, warm_start=False), XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=-1, num_parallel_tree=1,
             objective='reg:squarederror', random_state=42, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='auto',
             validate_parameters=1, verbosity=0)]

### Stacking

In [27]:
stacker = stack_models(top3)

In [28]:
lightgbm = create_model("lightgbm")
stacker2 = stack_models(top3, meta_model=lightgbm)

## Experiment Logging

In [29]:
# to start the MLFlow server from notebook:
# !mlflow ui